INSERT INTO PRODUCT(ID, NAME, PRODUCT_CODE, DESCRIPTION) VALUES (1000, 'Coca Cola', 'PRO_CC', 'another variant of sugar');
INSERT INTO PRODUCT(ID, NAME, PRODUCT_CODE, DESCRIPTION) VALUES (1001, 'Sugar', 'PRO_SG', '');
INSERT INTO PRODUCT(ID, NAME, PRODUCT_CODE, DESCRIPTION) VALUES(1003, 'Playstation 4', 'PRO_PS4', 'Gaming console');

